# Copyright 2026 Canonical Ltd.  This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

"""Performance tests for commissioning output processing.

`process_lxd_results` is the hook that turns the output of the
`50-maas-01-commissioning` script into nodes, NUMA nodes, interfaces, block
devices, node devices and node metadata. It runs once per commissioned node,
so its cost scales directly with fleet size, but nothing in `src/perftests`
covered it until now.

Structure copied from `src/perftests/maasserver/models/test_machine.py` and
`src/perftests/maasserver/dns/test_config.py`.

Like the rest of `src/perftests`, these tests record timing, SQL query count
and SQL query time; they do **not** assert on any of them. There is no
threshold and no regression gate anywhere in the repo, so the numbers are for
a human to compare between two runs. The assertions that are present only
check that the measured call did real work, so a run that silently processed
nothing is not mistaken for a fast one.

Three states are selectable with `MAAS_PERF_HOOKS_STATE`, so the cost of the
hardware profile feature can be separated from the cost of the commissioning
parsing it sits next to:

``base``
    `_populate_hardware_profile` disabled entirely. Approximates the code
    before the hardware profile feature was added.
``full`` (default)
    Unmodified `process_lxd_results`, exactly as it ships.
``build_only``
    The hardware profile is built from the commissioning output as usual, but
    the resulting row is not written. The difference between this and ``full``
    is the feature's database cost; the difference between this and ``base``
    is its parsing cost.

Payloads come from one of two places:

* By default, generated by `payloads.py`. `MAAS_PERF_PAYLOAD` selects the
  shape (`sampledata` or `large-server`) and `MAAS_PERF_NODES` the count.
* If `--commissioning-data-dir` is given, from real `*.json` commissioning
  output in that directory, one machine per file, in sorted filename order.
  Generated data is not used at all in that case, and the machine count is
  the number of files. `MAAS_PERF_NODES` may only be set alongside it if it
  agrees with that number.

Each recording notes how many payloads it processed and where they came from,
so two runs can be compared knowingly.

Real commissioning output carries serial numbers, MAC addresses, hostnames and
other hardware identifiers, so no payload corpus is kept in the repository; the
directory is supplied at run time. A synthetic corpus can be rendered from the
generators when only the plumbing is under test:

    bin/py -c "
    import json, pathlib
    from perftests.metadataserver.payloads import PAYLOAD_BUILDERS
    out = pathlib.Path('/tmp/corpus'); out.mkdir(exist_ok=True)
    for n in range(1, 4):
        payload = PAYLOAD_BUILDERS['sampledata'](n).render()
        (out / f'synthetic-{n:03}.json').write_text(json.dumps(payload))
    "
"""

import json
import os

import pytest

from maasserver.models import Machine
from metadataserver.builtin_scripts import hooks
from perftests.metadataserver.corpus import load_corpus
from perftests.metadataserver.payloads import PAYLOAD_BUILDERS

STATE = os.environ.get("MAAS_PERF_HOOKS_STATE", "full")
PAYLOAD = os.environ.get("MAAS_PERF_PAYLOAD", "sampledata")
DEFAULT_NODE_COUNT = 10


def _requested_node_count():
    """The explicitly requested node count, or None if unset."""
    value = os.environ.get("MAAS_PERF_NODES")
    return int(value) if value else None


def _generated_outputs(count):
    builder = PAYLOAD_BUILDERS[PAYLOAD]
    return [
        json.dumps(builder(index).render()).encode("utf-8")
        for index in range(1, count + 1)
    ]


@pytest.fixture(scope="session")
def commissioning_payloads(commissioning_data_dir):
    """Return (outputs, source_description, payload_names).

    `outputs` are the raw bytes handed to `process_lxd_results`.
    `payload_names` labels each one for error messages, and is None when the
    payloads were generated rather than read from disk.
    """
    requested_count = _requested_node_count()

    if commissioning_data_dir is None:
        count = (
            DEFAULT_NODE_COUNT if requested_count is None else requested_count
        )
        return _generated_outputs(count), f"generated:{PAYLOAD}", None

    payloads = load_corpus(commissioning_data_dir)
    if requested_count is not None and requested_count != len(payloads):
        raise AssertionError(
            f"MAAS_PERF_NODES={requested_count} conflicts with "
            f"--commissioning-data-dir {commissioning_data_dir}, which "
            f"supplies {len(payloads)} payload(s). One machine is seeded per "
            f"file; either unset MAAS_PERF_NODES or set it to "
            f"{len(payloads)}."
        )
    return (
        [payload.output for payload in payloads],
        str(commissioning_data_dir),
        [payload.name for payload in payloads],
    )


def _apply_state(monkeypatch):
    """Patch `hooks` for the selected state and return `process_lxd_results`."""
    if STATE == "full":
        return hooks.process_lxd_results

    if STATE == "base":
        monkeypatch.setattr(
            hooks, "_populate_hardware_profile", lambda node_id, data: None
        )
        return hooks.process_lxd_results

    if STATE == "build_only":

        def build_without_writing(node_id, data):
            from maasservicelayer.builders.hardwareprofile import (
                HardwareProfileBuilder,
            )

            HardwareProfileBuilder.from_commissioning_output(data, node_id)

        monkeypatch.setattr(
            hooks, "_populate_hardware_profile", build_without_writing
        )
        return hooks.process_lxd_results

    raise AssertionError(
        f"unknown MAAS_PERF_HOOKS_STATE {STATE!r}, "
        f"expected one of: base, full, build_only"
    )


def _label(index, payload_names):
    """Identify a payload in an error message."""
    if payload_names is None:
        return f"generated payload {index + 1}"
    return f"commissioning payload {payload_names[index]}"


def _process(process_lxd_results, machine, output, index, payload_names):
    """Process one payload, naming it if the processing path rejects it."""
    try:
        process_lxd_results(machine, output, 0)
    except Exception as error:
        raise AssertionError(
            f"{_label(index, payload_names)} failed to process: "
            f"{type(error).__name__}: {error}"
        ) from error


@pytest.mark.allow_transactions
def test_perf_process_lxd_results_single_node(
    perf, factory, monkeypatch, commissioning_payloads
):
    process_lxd_results = _apply_state(monkeypatch)
    outputs, source, payload_names = commissioning_payloads
    machine = factory.make_Machine()

    with perf.record(
        f"test_perf_process_lxd_results_single_node[{STATE}]",
        metadata={"payload_source": source, "payload_count": 1},
    ):
        _process(process_lxd_results, machine, outputs[0], 0, payload_names)

    machine.refresh_from_db()
    assert machine.cpu_count > 0
    assert machine.physicalblockdevice_set.count() > 0


@pytest.mark.allow_transactions
def test_perf_process_lxd_results_many_nodes(
    perf, factory, monkeypatch, commissioning_payloads
):
    process_lxd_results = _apply_state(monkeypatch)
    outputs, source, payload_names = commissioning_payloads
    machines = [factory.make_Machine() for _ in outputs]

    with perf.record(
        f"test_perf_process_lxd_results_many_nodes[{STATE}-{len(outputs)}]",
        metadata={"payload_source": source, "payload_count": len(outputs)},
    ):
        for index, (machine, output) in enumerate(
            zip(machines, outputs, strict=True)
        ):
            _process(
                process_lxd_results, machine, output, index, payload_names
            )

    processed = Machine.objects.filter(
        id__in=[machine.id for machine in machines], cpu_count__gt=0
    ).count()
    assert processed == len(outputs)
