name: run tests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: alemar99-test-build-env-${{ github.repository }}-${{ github.base_ref }}

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    permissions:
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Run linting
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ghcr.io/${{ github.repository_owner }}/your-image-name:your-tag \
            make lint

      - name: Run tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ghcr.io/${{ github.repository_owner }}/your-image-name:your-tag \
            make test
